### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by SoorajModi** [SoorajModi/socis_website#1]
Tasks
- Finish main header
  - Add SOCIS logo
  - Add padding to left and right
  - Improve mobile layout
  - (Optional) Add animation to header
- Add subheadings
  - Who are we subheading + content
  - What do we do subheading + content
  - Contact us subheading + content
  - Add images for each subheading
  - Recolor and change sizing of `LearnMoreBtn`
  - Make layout adaptable for mobile view

**Comment by danindugit** [comment]
I got this
