### ISSUE TITLE
Clubs Page

### ISSUE THREAD

**Issue by SoorajModi** [SoorajModi/socis_website#2]
- Add info for GCC
  - Add picture
  - Add title `Guelph Coding Community`
  - Add description for club
  - Add Learn More button which will link to GCC site/instagram
- Add info for GWICS
  - Add picture
  - Add title `Guelph Women in Computer Science`
  - Add description for club
  - Add Learn More button which will link to GWICS site/instagram
- Add info for DSC
  - Add picture
  - Add title `Developer Student Club`
  - Add description for club
  - Add Learn More button which will link to DSC site/instagram
- Buttons should its own component under `src/components/buttons/`, so that they can be reused
- Create layout so it looks good in mobile view

**Comment by Kayeris** [comment]
I would like to work on this
